ann_root: 'dataset/caption_dataset'
coco_gt_root: 'dataset/caption_dataset'

# size of vit model; base or large
vit: 'swin_b'
vit_grad_ckpt: False
vit_ckpt_layer: 0

batch_size: 35
init_lr: 5e-6 

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

# delete some tags that may disturb captioning
# 127: "quarter"; 2961: "back", 3351: "two"; 3265: "three"; 3338: "four"; 3355: "five"; 3359: "one"
delete_tag_index: [127,2961, 3351, 3265, 3338, 3355, 3359]